development:
  adapter: async

test:
  adapter: async

dev:
  adapter: async
  channel_prefix: avjunction_dev

staging:
  adapter: async
  channel_prefix: avjunction_staging

production:
  adapter: async
  channel_prefix: avjunction_production
