development:
  adapter: async

test:
  adapter: async

dev:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: avjunction_production

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: avjunction_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: avjunction_production
